food_recipes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('user.urls')),
    path('ingredient/', include('ingredient.urls')),
    path('recipes/', include('recipes.urls')),
]

user/urls.py
from django.urls import path
from .views import register_user,user_login,UserRegistrationAPIView, TokenObtainPairAPIView,UserLoginAPIView,UserListView,UserDetailByIDView


urlpatterns = [
    #page urls
    path('register/', register_user, name='register'),
    path('', user_login, name='login'),

    #api end points
    path('api/register/', UserRegistrationAPIView.as_view(), name='user-registration'),
    path('api/token/', TokenObtainPairAPIView.as_view(), name='token-obtain'),
    path('api/login/', UserLoginAPIView.as_view(), name='token-login'),
    path('api/users-list/', UserListView.as_view(), name='user-list'),
    path('api/user-id/<int:id>/', UserDetailByIDView.as_view(), name='user-id'),
]

recipes/models.py
from django.db import models
from user.models import User
from ingredient.models import Ingredient


#model for are Recipe's
class Recipe(models.Model):
    name = models.CharField(max_length=255)
    recipe_text = models.TextField()
    ingredients = models.ManyToManyField(Ingredient)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    average_rating = models.DecimalField(default=0.0, max_digits=3, decimal_places=2)  # To store average rating
    total_ratings = models.PositiveIntegerField(default=0)
    def __str__(self):
            return self.name

#Rating model for are recipe's
class RecipeRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=[(i, i) for i in range(1, 6)])

    class Meta:
        unique_together = ('user', 'recipe')

    def save(self, *args, **kwargs):
        if self.recipe.author != self.user:
            super(RecipeRating, self).save(*args, **kwargs)


            ratings = RecipeRating.objects.filter(recipe=self.recipe)
            total_ratings = ratings.count()
            average_rating = sum(rating.rating for rating in ratings) / total_ratings if total_ratings > 0 else 0
            self.recipe.average_rating = average_rating
            self.recipe.total_ratings = total_ratings
            self.recipe.save()

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


#simple user model for project
class User(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    def __str__(self):
        return self.email

templates/create_recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Yummy Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
</head>

<body style="background-color: #1a1814; color:white;">

<main id="main">
    <section id="book-a-table" class="book-a-table" style="background-color: #1a1814; color:white;">
        <div class="container" data-aos="fade-up">
            <div class="section-header">
                <h2>Add new RecipeS</h2>
                <p>Create <span>Your New</span> RecipE</p>
            </div>
            <div class="row g-0">
                <div class="col-lg-4 reservation-img" data-aos="zoom-out" data-aos-delay="200"><img
                        src="{% static 'assets/img/reservation.jpg' %}" width="100%" height="100%" alt="Tabler"
                        class="navbar-brand-image"></div>
                <div class="col-lg-8 d-flex align-items-center reservation-form-bg">
                    <form method="post" action="{% url 'create_recipe' %}" class="php-email-form" data-aos="fade-up"
                          data-aos-delay="100">
                        {% csrf_token %}
                        <div class="row gy-4">
                            <div class="col-lg-4 col-md-6">
                                <label for="id_name">Name:</label>
                                <input type="text" name="name" class="form-control" id="id_name"
                                       placeholder="Name of RecipE" data-rule="minlen:4">
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                <label for="id_author">Author:</label>
                                <select class="form-control" name="author" required="" id="id_author">
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                                </select>
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-4 col-md-6">
                                <label for="id_ingredients">Ingredients:</label>
                                <select class="form-control" name="ingredients" id="id_ingredients" multiple>
                                    {% for ingredient in ingredients %}
                                    <option value="{{ ingredient.id }}">{{ ingredient.name }}</option>
                                    {% endfor %}
                                </select>
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <textarea class="form-control" spellcheck="false" id="id_recipe_text" name="recipe_text"
                                      rows="8" required placeholder="Message"></textarea>
                            <div class="validate"></div>
                        </div>
                        <div class="text-center">
                            <button type="submit" style="background-color: burlywood;">Add new recipe</button>
                            <br>

                            <button type="submit" style="padding:2%; margin-top:2%;"><a href="{% url 'recipe_list' %}"
                                                                                        style="color:white;"> Go
                                back</a></button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
</main>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V1</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">

            <form class="login100-form validate-form" method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <span class="login100-form-title">
						Member Login
					</span>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="text" name="username" required id="id_username"
                           placeholder="Username">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
                </div>

                <div class="wrap-input100 validate-input">
                    <input class="input100" type="password" placeholder="Password" name="password" id="id_password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
                </div>
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Login
                    </button>
                </div>
                <div class="text-center p-t-136">
                    <a class="txt2" href="{% url 'register' %}">
                        Create your Account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/own_recipe_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Restaurantly Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/css/style.css' %}">

</head>

<body>
<header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto" href="{% url 'recipe_list'%}">List of Recipes</a></li>
          <li><a class="nav-link scrollto active" href="{% url 'own_recipe_list' %}">Own Recipes</a></li>
          <li><a class="nav-link scrollto " href="{% url 'top_ingredients' %}">Top 5 ingredients</a></li>
        </ul>

      </nav>
        <a href="{% url 'create_recipe' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add Recipe</a>
    </div>
  </header>
<main id="main" style="padding-top:5%;">
    <section id="menu" class="menu section-bg" >
        <div class="container" data-aos="fade-up">
            <div class="section-title">
                <h2>Recipes</h2>
                <p>Check Our Tasty Recipes</p>
            </div>
            <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                {% for recipe in own_recipes %}
                <div class="col-lg-6 menu-item filter-starters">
                    <div class="menu-content">
                        <a href="{% url 'recipe_detail' recipe_id=recipe.id %}"><h1>{{ recipe.name }}</h1></a><span>Rating {{ recipe.average_rating }}</span>
                    </div>
                    </br>
                    <div class="menu-ingredients">
                        {{ recipe.recipe_text }}
                    </div>
                    </br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6> Author: </h6>
                                <span>  {{ recipe.author.username }}</span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6>Ingredients: </h6>
                                {% for ingredient in recipe.ingredients.all %}
                                <span> {{ ingredient.name }}/ </span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <span></span>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
</body>
</html>

templates/recipe_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Restaurantly Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/css/style.css' %}">

</head>

<body>
<header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'recipe_list'%}">List of Recipes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'own_recipe_list' %}">Own Recipes</a></li>
                <li><a class="nav-link scrollto " href="{% url 'top_ingredients' %}">Top 5 ingredients</a></li>

            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <a href="{% url 'create_recipe' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add Recipe</a>
    </div>
</header>
<main id="main" style="padding-top:5%;">
    <section id="menu" class="menu section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Recipes</h2>
                <p>Check Our Tasty Recipes</p>
            </div>

            <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                <div class="col-lg-6 menu-item filter-starters">
                    <div class="menu-content">
                        <a href="{% url 'recipe_detail' recipe_id=recipe.id %}"><h1>{{ recipe.name }}</h1></a><span>Rating {{ recipe.average_rating }}</span>
                    </div>
                    </br>
                    <div class="menu-ingredients">
                        {{ recipe.recipe_text }}
                    </div>
                    </br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6> Author: </h6>
                                <span>  {{ recipe.author.username }}</span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6>Ingredients: </h6>
                                {% for ingredient in recipe.ingredients.all %}
                                <span> {{ ingredient.name }}/ </span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <form method="post" action="{% url 'recipe_detail' recipe.id %}">
                                    {% csrf_token %}
                                    <select name="rating" class="form-control" id="id_rating">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select><br>
                                    <button class="form-control" type="submit">Submit Rating</button>
                                </form>
                                <p><strong>Average Rating:</strong> {{ average_rating }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
</body>
</html>

templates/recipe_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Restaurantly Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/css/style.css' %}">

</head>

<body>
<header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'recipe_list'%}">List of Recipes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'own_recipe_list' %}">Own Recipes</a></li>
                <li><a class="nav-link scrollto " href="{% url 'top_ingredients' %}">Top 5 ingredients</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <a href="{% url 'create_recipe' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add Recipe</a>
    </div>
</header>
<main id="main" style="padding-top:5%;">
    <section id="menu" class="menu section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Recipes</h2>
                <p>Check Our Tasty Recipes</p>
            </div>
            <form method="GET" action="{% url 'recipe_list' %}">
                {% csrf_token %}
                <p>
                    <label class="form-class"  for="id_search_query">Search Recipes:</label>
                    <input class="form-class" type="text" name="search_query" id="id_search_query">
                </p>
                <p>
                    <label class="form-class"  for="id_min_ingredients">Minimum Ingredients:</label>
                    <input class="form-class"  type="number" name="min_ingredients"  id="id_min_ingredients">
                </p>
                <p>
                    <label class="form-class"  for="id_max_ingredients">Maximum Ingredients:</label>
                    <input class="form-class"  type="number" name="max_ingredients"  id="id_max_ingredients">
                </p>
                <button class="book-a-table-btn scrollto d-none d-lg-flex"  style="color:#cda45e;"  type="submit">Search &amp; Filter</button>
            </form>


            <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                {% for recipe in recipes %}
                <div class="col-lg-6 menu-item filter-starters">
                    <div class="menu-content">
                        <a href="{% url 'recipe_detail' recipe_id=recipe.id %}"><h1>{{ recipe.name }}</h1></a><span>Rating {{ recipe.average_rating }}</span>
                    </div>
                    </br>
                    <div class="menu-ingredients">
                        {{ recipe.recipe_text }}
                    </div>
                    </br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6> Author: </h6>
                                <span>  {{ recipe.author.username }}</span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="menu-ingredients">
                                <h6>Ingredients: </h6>
                                {% for ingredient in recipe.ingredients.all %}
                                <span> {{ ingredient.name }}/ </span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V1</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form" method="post" action="{% url 'register' %}">
                {% csrf_token %}
                <span class="login100-form-title">
						FooD RecipeS - Register
					</span>
                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text"  name="username" id="id_username" placeholder="Username" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
                </div>
                 <p> Password need to have: One uppercase, number and special character and min length 8 </p>
                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="password" required placeholder="Password" id="id_password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
                </div>
                 <p> User mail need to be verified by hunter.io </p>
                <div class="wrap-input100 validate-input" data-validate="Email is required">
                    <input class="input100"  type="email" name="email" id="id_email" placeholder="Email" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="First name is required">
                    <input class="input100"  type="text" name="first_name"  placeholder="First name" id="id_first_name" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-address-card" aria-hidden="true"></i>
						</span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Last name is required">
                    <input class="input100" type="text" name="last_name" placeholder="Last name" id="id_last_name" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-address-card" aria-hidden="true"></i>
						</span>
                </div>
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Register
                    </button>
                </div>
                <div class="text-center p-t-136">
                    <a class="txt2" href="{% url 'login' %}">
                        Login
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
                   {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/top_ingredients.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Restaurantly Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets_list/css/style.css' %}">

</head>

<body>
<header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto " href="{% url 'recipe_list'%}">List of Recipes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'own_recipe_list' %}">Own Recipes</a></li>
                <li><a class="nav-link scrollto active" href="{% url 'top_ingredients' %}">Top 5 ingredients</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <a href="{% url 'create_recipe' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add Recipe</a>
    </div>
</header>
<main id="main" style="padding-top:5%;">
    <section id="menu" class="menu section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Recipes</h2>
                <p>Check Our Tasty Recipes</p>
            </div>

            <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                {% for ingredient in top_ingredients %}
                <div class="col-lg-6 menu-item filter-starters">
                    <div class="menu-content">
                        <a href=""><h1>{{ ingredient.name }}</h1>
                        </a><span>Used in {{ ingredient.num_recipes }} recipes </span>
                    </div>
                    </br>

                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
</body>
</html>